//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G1ANT.Addon.Ocr.AbbyyFineReader.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("G1ANT.Addon.Ocr.AbbyyFineReader.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap document1 {
            get {
                object obj = ResourceManager.GetObject("document1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap document2 {
            get {
                object obj = ResourceManager.GetObject("document2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap document3 {
            get {
                object obj = ResourceManager.GetObject("document3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  /// /// ///Demographic data and estimates ///Area, Density, Capital City /// /// /// /// ///Projected ///Percent of ///Life /// /// /// /// /// /// ///Population ///Mid-2002 ///Population ///(millions) ///Population of ///Age ///Expectancy ///at Birth ///Area of Countries ///Pop. per ///Square /// /// /// /// ///(millions) ///2025 ///&lt;15 ///65+ ///(years) ///(square miles) ///Mile ///Capital City /// /// ///WORLD ///6,215 ///7,859 ///30 ///7 ///67 ///51,789,601 ///120 /// /// /// ///MORE DEVELOPED ///1,197 ///1.249 ///18 ///15 ///76 ///19,814,584 ///60 /// /// /// ///LESS DEVELOPED ///5.018 ///6,61 ///33 ///5 ///65 ///31,975,017 ///157 /// /// ///“ ///Egypt ///71.2 ///96.1 ///36 ///4 ///66 ///386,66 ///184 ///Cairo ///&lt;r ///1 1 ///Nigeria ///129.9 ///204.5 ///44 ///3 ///52 ///356 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string documentText {
            get {
                return ResourceManager.GetString("documentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dokument4 {
            get {
                object obj = ResourceManager.GetObject("dokument4", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
